cls
@echo off
arj a -r -m4 7DEN7NOC.ARJ 7DEN7NOC/
arj t 7DEN7NOC.ARJ
arj a -r -m4 ABUSE.ARJ ABUSE/
arj t ABUSE.ARJ
arj a -r -m4 ALADDIN.ARJ ALADDIN/
arj t ALADDIN.ARJ
arj a -r -m4 ALIENTRI.ARJ ALIENTRI/
arj t ALIENTRI.ARJ
arj a -r -m4 ALONEDRK.ARJ ALONEDRK/
arj t ALONEDRK.ARJ
arj a -r -m4 BELOGEST.ARJ BELOGEST/
arj t BELOGEST.ARJ
arj a -r -m4 BERUSKY.ARJ BERUSKY/
arj t BERUSKY.ARJ
arj a -r -m4 BLOCKOUT.ARJ BLOCKOUT/
arj t BLOCKOUT.ARJ
arj a -r -m4 BLOOD.ARJ BLOOD/
arj t BLOOD.ARJ
arj a -r -m4 CAESAR2.ARJ CAESAR2/
arj t CAESAR2.ARJ
arj a -r -m4 CASTLEM.ARJ CASTLEM/
arj t CASTLEM.ARJ
arj a -r -m4 CASTLEM2.ARJ CASTLEM2/
arj t CASTLEM2.ARJ
arj a -r -m4 CC.ARJ CC/
arj t CC.ARJ
arj a -r -m4 CHESS.ARJ CHESS/
arj t CHESS.ARJ
arj a -r -m4 CHESSGEN.ARJ CHESSGEN/
arj t CHESSGEN.ARJ
arj a -r -m4 CHESSPLA.ARJ CHESSPLA/
arj t CHESSPLA.ARJ
arj a -r -m4 CIV.ARJ CIV/
arj t CIV.ARJ
arj a -r -m4 DESCENT.ARJ DESCENT/
arj t DESCENT.ARJ
arj a -r -m4 DESCENT2.ARJ DESCENT2/
arj t DESCENT2.ARJ
arj a -r -m4 DOOM.ARJ DOOM/
arj t DOOM.ARJ
arj a -r -m4 DOOM2.ARJ DOOM2/
arj t DOOM2.ARJ
arj a -r -m4 DUKE2.ARJ DUKE2/
arj t DUKE2.ARJ
arj a -r -m4 DUKE3D.ARJ DUKE3D/
arj t DUKE3D.ARJ
arj a -r -m4 DUNE2.ARJ DUNE2/
arj t DUNE2.ARJ
arj a -r -m4 DUNE2S.ARJ DUNE2S/
arj t DUNE2S.ARJ
arj a -r -m4 GALZEME.ARJ GALZEME/
arj t GALZEME.ARJ
arj a -r -m4 GOBLINS2.ARJ GOBLINS2/
arj t GOBLINS2.ARJ
arj a -r -m4 GOBLINS3.ARJ GOBLINS3/
arj t GOBLINS3.ARJ
arj a -r -m4 HERETIC.ARJ HERETIC/
arj t HERETIC.ARJ
arj a -r -m4 HEXEN.ARJ HEXEN/
arj t HEXEN.ARJ
arj a -r -m4 HEXX.ARJ HEXX/
arj t HEXX.ARJ
arj a -r -m4 JAZZ.ARJ JAZZ/
arj t JAZZ.ARJ
arj a -r -m4 JILL.ARJ JILL/
arj t JILL.ARJ
arj a -r -m4 JS-WILLY.ARJ JS-WILLY/
arj t JS-WILLY.ARJ
arj a -r -m4 KEEN4.ARJ KEEN4/
arj t KEEN4.ARJ
arj a -r -m4 KEEN5.ARJ KEEN5/
arj t KEEN5.ARJ
arj a -r -m4 KEEN6.ARJ KEEN6/
arj t KEEN6.ARJ
arj a -r -m4 KEEN7.ARJ KEEN7/
arj t KEEN7.ARJ
arj a -r -m4 KEEN8.ARJ KEEN8/
arj t KEEN8.ARJ
arj a -r -m4 LEMMCHS.ARJ LEMMCHS/
arj t LEMMCHS.ARJ
arj a -r -m4 LEMMINGS.ARJ LEMMINGS/
arj t LEMMINGS.ARJ
arj a -r -m4 LHX.ARJ LHX/
arj t LHX.ARJ
arj a -r -m4 LODERUN.ARJ LODERUN/
arj t LODERUN.ARJ
arj a -r -m4 M-CHESS.ARJ M-CHESS/
arj t M-CHESS.ARJ
arj a -r -m4 MANIC.ARJ MANIC/
arj t MANIC.ARJ
arj a -r -m4 MLICNAK.ARJ MLICNAK/
arj t MLICNAK.ARJ
arj a -r -m4 MONKEY.ARJ MONKEY/
arj t MONKEY.ARJ
arj a -r -m4 NAM.ARJ NAM/
arj t NAM.ARJ
arj a -r -m4 OSKAR.ARJ OSKAR/
arj t OSKAR.ARJ
arj a -r -m4 PERESTR.ARJ PERESTR/
arj t PERESTR.ARJ
arj a -r -m4 PREH2.ARJ PREH2/
arj t PREH2.ARJ
arj a -r -m4 PRINCE.ARJ PRINCE/
arj t PRINCE.ARJ
arj a -r -m4 PRINCE2.ARJ PRINCE2/
arj t PRINCE2.ARJ
arj a -r -m4 PRSI.ARJ PRSI/
arj t PRSI.ARJ
arj a -r -m4 PSION213.ARJ PSION213/
arj t PSION213.ARJ
arj a -r -m4 PTOMB.ARJ PTOMB/
arj t PTOMB.ARJ
arj a -r -m4 PUSHOVER.ARJ PUSHOVER/
arj t PUSHOVER.ARJ
arj a -r -m4 QUAKE.ARJ QUAKE/
arj t QUAKE.ARJ
arj a -r -m4 RA.ARJ RA/
arj t RA.ARJ
arj a -r -m4 RAPTOR.ARJ RAPTOR/
arj t RAPTOR.ARJ
arj a -r -m4 RE.ARJ RE/
arj t RE.ARJ
arj a -r -m4 REDNECK.ARJ REDNECK/
arj t REDNECK.ARJ
arj a -r -m4 ROOT.ARJ ROOT/
arj t ROOT.ARJ
arj a -r -m4 SABOTEUR.ARJ SABOTEUR/
arj t SABOTEUR.ARJ
arj a -r -m4 SIM2000.ARJ SIM2000/
arj t SIM2000.ARJ
arj a -r -m4 SIMCITY.ARJ SIMCITY/
arj t SIMCITY.ARJ
arj a -r -m4 SOKOBAN.ARJ SOKOBAN/
arj t SOKOBAN.ARJ
arj a -r -m4 STINYNOC.ARJ STINYNOC/
arj t STINYNOC.ARJ
arj a -r -m4 TERMVELO.ARJ TERMVELO/
arj t TERMVELO.ARJ
arj a -r -m4 THOSPITA.ARJ THOSPITA/
arj t THOSPITA.ARJ
arj a -r -m4 TOMBGOLD.ARJ TOMBGOLD/
arj t TOMBGOLD.ARJ
arj a -r -m4 TOMBRAID.ARJ TOMBRAID/
arj t TOMBRAID.ARJ
arj a -r -m4 TYCOON.ARJ TYCOON/
arj t TYCOON.ARJ
arj a -r -m4 TYCOON2.ARJ TYCOON2/
arj t TYCOON2.ARJ
arj a -r -m4 UFO.ARJ UFO/
arj t UFO.ARJ
arj a -r -m4 VLAK.ARJ VLAK/
arj t VLAK.ARJ
arj a -r -m4 WAR.ARJ WAR/
arj t WAR.ARJ
arj a -r -m4 WAR2.ARJ WAR2/
arj t WAR2.ARJ
arj a -r -m4 WHAVEN.ARJ WHAVEN/
arj t WHAVEN.ARJ
arj a -r -m4 WOLF.ARJ WOLF/
arj t WOLF.ARJ
arj a -r -m4 XMASLEM.ARJ XMASLEM/
arj t XMASLEM.ARJ
@echo on
